# app/docker-compose.yml

version: '3.8'

services:
  server:
    build: ./server
    container_name: my-app-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx ts-node server.ts"

  client:
    build: ./client
    container_name: my-app-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - server
