sequenceDiagram
  autonumber
  participant C as Client
  participant API as Order API
  participant H as Command Handler
  participant ES as Event Store
  participant P as Projector
  participant R as Read DB

  C->>API: POST /orders { items, payment }
  API->>H: validate+build Command
  H->>ES: append(OrderCreated, PaymentRequested)
  Note over H: Outbox: IntegrationEvent(PaymentRequested)

  P-->>ES: subscribe(stream)
  ES-->>P: event(OrderCreated)
  P->>R: upsert read model

  C->>API: GET /orders/{id}
  API->>R: query
  R-->>API: OrderView
  API-->>C: 200 OK
